"""create initial contract review schema

Revision ID: c2b09b0030df
Revises:
Create Date: 2026-10-07 13:12:00.406135
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c2b09b0030df"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "processing", "completed", "failed", name="contract_status"
            ),
            nullable=False,
        ),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("renewal_date", sa.Date(), nullable=True),
        sa.Column("contract_type", sa.String(length=255), nullable=True),
        sa.Column("parties", sa.JSON(), nullable=False),
        sa.Column("governing_law", sa.String(length=255), nullable=True),
        sa.Column("payment_terms", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contracts_contract_type"), "contracts", ["contract_type"], unique=False
    )
    op.create_index(op.f("ix_contracts_status"), "contracts", ["status"], unique=False)
    op.create_index(op.f("ix_contracts_title"), "contracts", ["title"], unique=False)
    op.create_table(
        "clauses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("clause_type", sa.String(length=64), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clauses_clause_type"), "clauses", ["clause_type"], unique=False
    )
    op.create_index(
        op.f("ix_clauses_contract_id"), "clauses", ["contract_id"], unique=False
    )
    op.create_table(
        "contract_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "contract_id", "chunk_index", name="uq_contract_chunk_index"
        ),
    )
    op.create_index(
        op.f("ix_contract_chunks_contract_id"),
        "contract_chunks",
        ["contract_id"],
        unique=False,
    )
    op.create_table(
        "obligations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("responsible_party", sa.String(length=255), nullable=True),
        sa.Column("counterparty", sa.String(length=255), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("recurring_frequency", sa.String(length=255), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "critical", name="obligation_priority"),
            nullable=False,
        ),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_obligations_contract_id"), "obligations", ["contract_id"], unique=False
    )
    op.create_index(
        op.f("ix_obligations_priority"), "obligations", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_obligations_responsible_party"),
        "obligations",
        ["responsible_party"],
        unique=False,
    )
    op.create_table(
        "risks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("low", "medium", "high", "critical", name="risk_level"),
            nullable=False,
        ),
        sa.Column("why_it_matters", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risks_category"), "risks", ["category"], unique=False)
    op.create_index(
        op.f("ix_risks_contract_id"), "risks", ["contract_id"], unique=False
    )
    op.create_index(op.f("ix_risks_level"), "risks", ["level"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risks_level"), table_name="risks")
    op.drop_index(op.f("ix_risks_contract_id"), table_name="risks")
    op.drop_index(op.f("ix_risks_category"), table_name="risks")
    op.drop_table("risks")
    op.drop_index(op.f("ix_obligations_responsible_party"), table_name="obligations")
    op.drop_index(op.f("ix_obligations_priority"), table_name="obligations")
    op.drop_index(op.f("ix_obligations_contract_id"), table_name="obligations")
    op.drop_table("obligations")
    op.drop_index(op.f("ix_contract_chunks_contract_id"), table_name="contract_chunks")
    op.drop_table("contract_chunks")
    op.drop_index(op.f("ix_clauses_contract_id"), table_name="clauses")
    op.drop_index(op.f("ix_clauses_clause_type"), table_name="clauses")
    op.drop_table("clauses")
    op.drop_index(op.f("ix_contracts_title"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_status"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_contract_type"), table_name="contracts")
    op.drop_table("contracts")
    # ### end Alembic commands ###
